"""
AgriSmart AI — Digital Quality Passport Service
=================================================
Assembles and formats the complete Digital Quality Passport for a cultivation batch.
Generates:
  - Batch metadata, harvest dates, cultivation method
  - Quality test results matrix with pass/fail badges
  - Attached lab reports and accreditation proof
  - Shareable read-only public verification token
  - QR Code image for packaging labels
"""

import io
import base64
from datetime import datetime, timezone
def generate_qr_code_base64(data_url: str) -> str:
    """Generate a base64 encoded PNG QR code or SVG fallback."""
    try:
        import qrcode
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_M,
            box_size=8,
            border=2,
        )
        qr.add_data(data_url)
        qr.make(fit=True)

        img = qr.make_image(fill_color="black", back_color="white")
        buffered = io.BytesIO()
        img.save(buffered, format="PNG")
        img_str = base64.b64encode(buffered.getvalue()).decode("utf-8")
        return f"data:image/png;base64,{img_str}"
    except Exception:
        # Fallback 1x1 placeholder base64
        dummy_png = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="
        return f"data:image/png;base64,{dummy_png}"


def compile_passport_summary(batch) -> dict:
    """
    Compile full passport JSON structure from batch and related test records.
    """
    p = batch.product
    proj = batch.project

    tests_summary = []
    pass_count = 0
    fail_count = 0

    for tr in batch.test_results:
        status = tr.pass_fail or "pass"
        if status == "pass":
            pass_count += 1
        elif status == "fail":
            fail_count += 1

        tests_summary.append({
            "id": tr.id,
            "test_name": tr.test_name_as_reported or "Standard Quality Test",
            "result_value": tr.result_value,
            "specification_limit": tr.specification_limit,
            "pass_fail": status,
            "verified": not tr.needs_manual_verification,
        })

    overall_status = "CERTIFIED_PASS" if (fail_count == 0 and len(tests_summary) > 0) else ("FAIL" if fail_count > 0 else "PENDING_TESTS")

    return {
        "passport_version": "1.0",
        "batch_code": batch.batch_code,
        "product_name": p.common_name if p else "N/A",
        "scientific_name": p.scientific_name if p else None,
        "method": p.method.display_name if (p and p.method) else "Soil-Free",
        "producer_project": proj.name if proj else "AgriSmart Producer",
        "start_date": batch.start_date.isoformat() if batch.start_date else None,
        "harvest_date": batch.actual_harvest_date.isoformat() if batch.actual_harvest_date else (batch.expected_harvest_date.isoformat() if batch.expected_harvest_date else None),
        "actual_yield_kg": float(batch.actual_yield_kg) if batch.actual_yield_kg is not None else None,
        "status": batch.status,
        "overall_quality_status": overall_status,
        "tests_conducted_count": len(tests_summary),
        "tests_passed_count": pass_count,
        "tests_failed_count": fail_count,
        "test_results": tests_summary,
        "lab_reports_attached": batch.lab_reports.count(),
        "disclaimer": "This Digital Quality Assurance Certificate is generated by AgriSmart AI based on producer-uploaded lab reports and verified test records. It facilitates buyer verification and does not replace statutory certification.",
        "compiled_at": datetime.now(timezone.utc).isoformat(),
    }
