"""Initial database schema

Revision ID: 348787399ac7
Revises: 
Create Date: 2026-09-26 17:04:53.853670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348787399ac7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultivation_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('soil_required', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('laboratories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('accreditation', sa.String(length=200), nullable=True),
    sa.Column('accreditation_verified', sa.Boolean(), nullable=True),
    sa.Column('typical_turnaround_days_min', sa.Integer(), nullable=True),
    sa.Column('typical_turnaround_days_max', sa.Integer(), nullable=True),
    sa.Column('indicative_cost_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(length=300), nullable=True),
    sa.Column('data_verified_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logistics_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=100), nullable=False),
    sa.Column('distance_km_min', sa.Integer(), nullable=True),
    sa.Column('distance_km_max', sa.Integer(), nullable=True),
    sa.Column('cost_inr_per_kg_min', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cost_inr_per_kg_max', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cold_chain', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(length=300), nullable=True),
    sa.Column('valid_as_of', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('quality_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=300), nullable=False),
    sa.Column('test_category', sa.Enum('legal', 'buyer', 'voluntary', 'recommended'), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('sample_type', sa.String(length=200), nullable=True),
    sa.Column('standard_reference', sa.String(length=300), nullable=True),
    sa.Column('applicable_jurisdiction', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(length=300), nullable=True),
    sa.Column('data_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lab_capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('capability_area', sa.String(length=300), nullable=False),
    sa.Column('sample_types_accepted', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_capabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_capabilities_laboratory_id'), ['laboratory_id'], unique=False)

    op.create_table('lab_test_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('quality_test_id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('indicative_cost_inr', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('turnaround_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.ForeignKeyConstraint(['quality_test_id'], ['quality_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_test_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_test_mappings_laboratory_id'), ['laboratory_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=200), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('typical_harvest_days_min', sa.Integer(), nullable=True),
    sa.Column('typical_harvest_days_max', sa.Integer(), nullable=True),
    sa.Column('yield_kg_per_sqm_cycle_min', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('yield_kg_per_sqm_cycle_max', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(length=300), nullable=True),
    sa.Column('data_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['method_id'], ['cultivation_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_method_id'), ['method_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'deactivated', 'pending_verification'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('buyer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=True),
    sa.Column('business_type', sa.String(length=200), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('collection_radius_km', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cost_assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('electricity_inr_per_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('water_inr_per_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('nutrients_inr_per_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('seeds_spawn_inr_per_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('substrate_inr_per_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('labor_inr_per_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('maintenance_inr_per_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('packaging_inr_per_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('transport_inr_per_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('indicative_price_inr_per_kg_min', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('indicative_price_inr_per_kg_max', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('assumption_notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=300), nullable=True),
    sa.Column('valid_as_of', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('end_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('end_user_type', sa.String(length=200), nullable=False),
    sa.Column('end_product', sa.String(length=300), nullable=True),
    sa.Column('typical_quality_grade', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('end_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_end_users_industry_id'), ['industry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_end_users_product_id'), ['product_id'], unique=False)

    op.create_table('environmental_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('temp_min_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_max_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_optimum_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_min_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_max_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('light_requirement', sa.String(length=200), nullable=True),
    sa.Column('photoperiod_hours', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('co2_ppm_min', sa.Integer(), nullable=True),
    sa.Column('co2_ppm_max', sa.Integer(), nullable=True),
    sa.Column('ventilation_required', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('infrastructure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tanks_required', sa.Boolean(), nullable=True),
    sa.Column('pumps_required', sa.Boolean(), nullable=True),
    sa.Column('racks_required', sa.Boolean(), nullable=True),
    sa.Column('lighting_required', sa.Boolean(), nullable=True),
    sa.Column('climate_control_required', sa.Boolean(), nullable=True),
    sa.Column('growing_media', sa.String(length=300), nullable=True),
    sa.Column('infrastructure_details', sa.JSON(), nullable=True),
    sa.Column('estimated_capex_inr_per_sqm_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_capex_inr_per_sqm_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_source', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('market_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sales_channel', sa.String(length=200), nullable=True),
    sa.Column('geography', sa.String(length=200), nullable=True),
    sa.Column('price_inr_per_kg_min', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price_inr_per_kg_max', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('demand_level', sa.String(length=50), nullable=True),
    sa.Column('price_trend', sa.String(length=50), nullable=True),
    sa.Column('data_source', sa.String(length=300), nullable=False),
    sa.Column('observed_at', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_observations_product_id'), ['product_id'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('training_data_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrient_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('nitrogen_n', sa.String(length=100), nullable=True),
    sa.Column('phosphorus_p', sa.String(length=100), nullable=True),
    sa.Column('potassium_k', sa.String(length=100), nullable=True),
    sa.Column('calcium_ca', sa.String(length=100), nullable=True),
    sa.Column('magnesium_mg', sa.String(length=100), nullable=True),
    sa.Column('sulfur_s', sa.String(length=100), nullable=True),
    sa.Column('iron_fe', sa.String(length=100), nullable=True),
    sa.Column('zinc_zn', sa.String(length=100), nullable=True),
    sa.Column('manganese_mn', sa.String(length=100), nullable=True),
    sa.Column('copper_cu', sa.String(length=100), nullable=True),
    sa.Column('boron_b', sa.String(length=100), nullable=True),
    sa.Column('molybdenum_mo', sa.String(length=100), nullable=True),
    sa.Column('carbon_source', sa.String(length=200), nullable=True),
    sa.Column('trace_minerals', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('nutrition_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('serving_basis', sa.String(length=50), nullable=True),
    sa.Column('calories_kcal', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('carbohydrates_g', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('vitamin_a_ug', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('vitamin_b12_ug', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('vitamin_c_mg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('vitamin_d_ug', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('vitamin_e_mg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('vitamin_k_ug', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('calcium_mg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('iron_mg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('magnesium_mg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('potassium_mg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('zinc_mg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('data_source', sa.String(length=300), nullable=True),
    sa.Column('data_version', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('packaging_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('packaging_type', sa.String(length=200), nullable=False),
    sa.Column('unit_size_kg', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('cold_chain_required', sa.Boolean(), nullable=True),
    sa.Column('estimated_cost_inr', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('suitable_channels', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_test_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quality_test_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('applicable_markets', sa.String(length=300), nullable=True),
    sa.Column('buyer_requirement', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quality_test_id'], ['quality_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_test_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_test_requirements_product_id'), ['product_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', 'deleted'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('sales_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(length=200), nullable=False),
    sa.Column('typical_commission_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('typical_spoilage_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cold_chain_required', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('substrate_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('primary_substrate', sa.String(length=300), nullable=True),
    sa.Column('alternative_substrates', sa.Text(), nullable=True),
    sa.Column('substrate_moisture_pct_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('substrate_moisture_pct_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sterilization_required', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('water_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('water_litres_per_kg_min', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('water_litres_per_kg_max', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ph_min', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ph_max', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ec_min_ms_cm', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('ec_max_ms_cm', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('water_recycling_potential', sa.String(length=50), nullable=True),
    sa.Column('water_quality_notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'harvested', 'sold', 'archived'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('actual_harvest_date', sa.Date(), nullable=True),
    sa.Column('area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_yield_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_batch_code'), ['batch_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_batches_project_id'), ['project_id'], unique=False)

    op.create_table('break_even_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('fixed_cost_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variable_cost_per_kg_inr', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('selling_price_per_kg_inr', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('break_even_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('break_even_cycles', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('break_even_months', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyer_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_profile_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('required_quantity_kg_per_week', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('required_quantity_kg_per_month', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('quality_grade', sa.String(length=100), nullable=True),
    sa.Column('required_tests', sa.JSON(), nullable=True),
    sa.Column('min_price_inr_per_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('target_price_inr_per_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('packaging_requirements', sa.Text(), nullable=True),
    sa.Column('delivery_requirements', sa.Text(), nullable=True),
    sa.Column('cold_chain_required', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_profile_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buyer_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buyer_requirements_buyer_profile_id'), ['buyer_profile_id'], unique=False)

    op.create_table('digital_twin_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('simulation_label', sa.String(length=200), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('raw_input', sa.String(length=500), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('geocoding_source', sa.String(length=100), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(), nullable=True),
    sa.Column('current_weather', sa.JSON(), nullable=True),
    sa.Column('forecast', sa.JSON(), nullable=True),
    sa.Column('historical_climate', sa.JSON(), nullable=True),
    sa.Column('weather_source', sa.String(length=100), nullable=True),
    sa.Column('weather_retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('split', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('objective_type', sa.String(length=50), nullable=False),
    sa.Column('secondary_objective', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('optimization_objective', sa.String(length=100), nullable=True),
    sa.Column('allocations', sa.JSON(), nullable=True),
    sa.Column('total_expected_revenue_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_expected_profit_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('objective_type', sa.String(length=50), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('weight_profile', sa.JSON(), nullable=True),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'complete', 'failed'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_runs_project_id'), ['project_id'], unique=False)

    op.create_table('resource_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('available_area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('area_type', sa.Enum('indoor', 'outdoor', 'greenhouse', 'rooftop', 'hybrid'), nullable=True),
    sa.Column('available_capital_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('water_available_litres_day', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('water_constraints', sa.Text(), nullable=True),
    sa.Column('manpower_workers', sa.Integer(), nullable=True),
    sa.Column('manpower_hours_per_day', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('existing_infrastructure', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('rotation_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('plan_year', sa.Integer(), nullable=True),
    sa.Column('monthly_plan', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scenario_type', sa.Enum('base', 'what_if', 'portfolio'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('capital_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('selling_price_inr_per_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('yield_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('electricity_inr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('labor_inr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('packaging_inr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transport_inr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revenue_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('opex_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('profit_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('roi_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('net_realizable_price_inr', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_project_id'), ['project_id'], unique=False)

    op.create_table('yield_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yield_kg_per_sqm', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('total_yield_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cycles_per_year', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('annual_yield_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyer_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('producer_project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'negotiating', 'accepted', 'rejected', 'closed'), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_requirement_id'], ['buyer_requirements.id'], ),
    sa.ForeignKeyConstraint(['producer_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buyer_inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buyer_inquiries_status'), ['status'], unique=False)

    op.create_table('buyer_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_requirement_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('compatibility_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('match_reasons', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_requirement_id'], ['buyer_requirements.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('ocr_status', sa.Enum('pending', 'complete', 'failed', 'manual_review'), nullable=True),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_extracted', sa.JSON(), nullable=True),
    sa.Column('ocr_confidence_flags', sa.JSON(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_reports_batch_id'), ['batch_id'], unique=False)

    op.create_table('quality_passports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('qr_data', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    with op.batch_alter_table('quality_passports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_passports_share_token'), ['share_token'], unique=True)

    op.create_table('recommendation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('feasible', sa.Boolean(), nullable=True),
    sa.Column('feasibility_notes', sa.JSON(), nullable=True),
    sa.Column('suitability_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('component_scores', sa.JSON(), nullable=True),
    sa.Column('estimated_yield_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('estimated_revenue_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estimated_opex_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estimated_profit_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estimated_roi_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sustainability_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cultivate_to_market_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['recommendation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_results_run_id'), ['run_id'], unique=False)

    op.create_table('feature_importance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=200), nullable=False),
    sa.Column('importance_value', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('direction', sa.Enum('positive', 'negative', 'neutral'), nullable=True),
    sa.Column('human_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['recommendation_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_importance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_importance_result_id'), ['result_id'], unique=False)

    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('buyer_inquiry_id', sa.Integer(), nullable=True),
    sa.Column('required_quantity_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('required_by_date', sa.Date(), nullable=True),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_inquiry_id'], ['buyer_inquiries.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('lab_report_id', sa.Integer(), nullable=True),
    sa.Column('quality_test_id', sa.Integer(), nullable=True),
    sa.Column('test_name_as_reported', sa.String(length=300), nullable=True),
    sa.Column('result_value', sa.String(length=200), nullable=True),
    sa.Column('result_unit', sa.String(length=100), nullable=True),
    sa.Column('specification_limit', sa.String(length=200), nullable=True),
    sa.Column('pass_fail', sa.Enum('pass', 'fail', 'inconclusive', 'not_applicable'), nullable=True),
    sa.Column('needs_manual_verification', sa.Boolean(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['lab_report_id'], ['lab_reports.id'], ),
    sa.ForeignKeyConstraint(['quality_test_id'], ['quality_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_results_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_results_batch_id'))

    op.drop_table('test_results')
    op.drop_table('production_orders')
    with op.batch_alter_table('feature_importance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_importance_result_id'))

    op.drop_table('feature_importance')
    with op.batch_alter_table('recommendation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_results_run_id'))

    op.drop_table('recommendation_results')
    with op.batch_alter_table('quality_passports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_passports_share_token'))

    op.drop_table('quality_passports')
    with op.batch_alter_table('lab_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_reports_batch_id'))

    op.drop_table('lab_reports')
    op.drop_table('buyer_matches')
    with op.batch_alter_table('buyer_inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buyer_inquiries_status'))

    op.drop_table('buyer_inquiries')
    op.drop_table('yield_estimates')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_project_id'))

    op.drop_table('scenarios')
    op.drop_table('rotation_plans')
    op.drop_table('resource_profiles')
    with op.batch_alter_table('recommendation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_runs_project_id'))

    op.drop_table('recommendation_runs')
    op.drop_table('portfolios')
    op.drop_table('objectives')
    op.drop_table('model_metrics')
    op.drop_table('locations')
    op.drop_table('digital_twin_runs')
    with op.batch_alter_table('buyer_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buyer_requirements_buyer_profile_id'))

    op.drop_table('buyer_requirements')
    op.drop_table('break_even_runs')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_project_id'))
        batch_op.drop_index(batch_op.f('ix_batches_batch_code'))

    op.drop_table('batches')
    op.drop_table('water_requirements')
    op.drop_table('user_profiles')
    op.drop_table('system_settings')
    op.drop_table('substrate_requirements')
    op.drop_table('sales_channels')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_status'))

    op.drop_table('projects')
    with op.batch_alter_table('product_test_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_test_requirements_product_id'))

    op.drop_table('product_test_requirements')
    op.drop_table('packaging_options')
    op.drop_table('nutrition_data')
    op.drop_table('nutrient_requirements')
    op.drop_table('model_versions')
    with op.batch_alter_table('market_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_observations_product_id'))

    op.drop_table('market_observations')
    op.drop_table('infrastructure')
    op.drop_table('environmental_requirements')
    with op.batch_alter_table('end_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_end_users_product_id'))
        batch_op.drop_index(batch_op.f('ix_end_users_industry_id'))

    op.drop_table('end_users')
    op.drop_table('cost_assumptions')
    op.drop_table('buyer_profiles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('role_permissions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_method_id'))

    op.drop_table('products')
    with op.batch_alter_table('lab_test_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_test_mappings_laboratory_id'))

    op.drop_table('lab_test_mappings')
    with op.batch_alter_table('lab_capabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_capabilities_laboratory_id'))

    op.drop_table('lab_capabilities')
    op.drop_table('roles')
    op.drop_table('quality_tests')
    op.drop_table('permissions')
    op.drop_table('logistics_rates')
    op.drop_table('laboratories')
    op.drop_table('industries')
    op.drop_table('data_sources')
    op.drop_table('cultivation_methods')
    # ### end Alembic commands ###
